-- 1. Create a database & Schema
-- CREATE DATABASE TIMETRAVEL_EXERCISE;
-- CREATE SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

-- 2. Create a customers table
-- CREATE TABLE CUSTOMER AS
-- SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
-- LIMIT 500;

-- 3. Drop the schema (assuming it happened by accident)
-- DROP SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

-- 4. Verify table doesn't exist anymore

-- 5. Undrop Schema
-- Questions for this assignment

-- Have you been able to undrop the schema and bring back the table again?


CREATE OR REPLACE DATABASE TIMETRAVEL_EXERCISE;

CREATE OR REPLACE SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

CREATE OR REPLACE TABLE CUSTOMER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
LIMIT 500;

DROP SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;


SELECT * FROM TIMETRAVEL_EXERCISE.COMPANY_X.CUSTOMER;

UNDROP SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

SELECT * FROM TIMETRAVEL_EXERCISE.COMPANY_X.CUSTOMER;