-- 1. Create exercise table
-- -- Switch to role of accountadmin --
 
-- USE ROLE ACCOUNTADMIN;
-- USE DATABASE DEMO_DB;
-- USE WAREHOUSE COMPUTE_WH;
 
-- CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.SUPPLIER
-- AS
-- SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."SUPPLIER";

-- 2. Create a clone of that table called SUPPLIER_CLONE

-- 3. Update the clone table and copy the query id
-- UPDATE SUPPLIER_CLONE
-- SET S_PHONE='###';
 
-- --> Query ID:

-- 4. Create another clone from the updated clone using the time travel feature to clone before the update has been executed.

-- Ans: Yes since it is an independent object.


USE ROLE ACCOUNTADMIN;
USE DATABASE DEMO_DB;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.SUPPLIER
AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."SUPPLIER";

CREATE TRANSIENT TABLE DEMO_DB.PUBLIC.SUPPLIER_CLONE
CLONE DEMO_DB.PUBLIC.SUPPLIER;

Select * from DEMO_DB.PUBLIC.SUPPLIER_CLONE;

UPDATE DEMO_DB.PUBLIC.SUPPLIER_CLONE
SET S_PHONE='###';

-- Query_id = 01c3c6db-3202-9995-0016-32ae00069e76


CREATE TRANSIENT TABLE DEMO_DB.PUBLIC.SUPPLIER_CLONE_OF_CLONE
CLONE DEMO_DB.PUBLIC.SUPPLIER_CLONE BEFORE (STATEMENT => '01c3c6db-3202-9995-0016-32ae00069e76');

SELECT * FROM DEMO_DB.PUBLIC.SUPPLIER_CLONE_OF_CLONE;

DROP TABLE DEMO_DB.PUBLIC.SUPPLIER;
